plugins {
    id 'application'
}

apply from: "$rootDir/buildSrc/copy-libs.gradle"

dependencies {
    implementation project(':common')
    implementation fileTree(dir: 'lib', include: '*.jar')
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.77'
}

jar {
    // We make a "fat" jar to store module dependencies and classes in one archive
    from {
        configurations.compileClasspath.filter { it.exists() }.collect { it.isDirectory() ? it : zipTree(it) }
    }
    // We do not need any signing-related files taken from dependencies
    exclude 'META-INF/*.RSA', 'META-INF/*.SF', 'META-INF/*.DSA'
}
